-- Phase 1 / Batch 1: Real Indonesian World foundation
-- Source-backed regional/city registry. No synthetic GDP/UMK values are invented.
create table if not exists public.game_regions (
  id bigint generated by default as identity primary key,
  region_key text not null unique,
  name text not null,
  region_type text not null check (region_type in ('province','special_region')),
  island_group text,
  metadata jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_cities (
  id bigint generated by default as identity primary key,
  city_key text not null unique,
  name text not null unique,
  region_id bigint not null references public.game_regions(id) on delete restrict,
  city_type text not null default 'city' check (city_type in ('city','regency')),
  population_estimate bigint,
  population_year integer,
  gdp_current_idr bigint,
  gdp_constant_idr bigint,
  gdp_year integer,
  gdp_growth_pct numeric(7,3),
  minimum_wage_idr bigint,
  minimum_wage_year integer,
  data_status text not null default 'legacy_pending' check (data_status in ('verified','legacy_pending')),
  geography jsonb not null default '{}'::jsonb,
  economy_profile jsonb not null default '{}'::jsonb,
  human_resources jsonb not null default '{}'::jsonb,
  natural_resources jsonb not null default '{}'::jsonb,
  political_profile jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists game_cities_region_idx on public.game_cities(region_id);
create index if not exists game_cities_active_idx on public.game_cities(active);

alter table public.game_regions enable row level security;
alter table public.game_cities enable row level security;
revoke all on public.game_regions from anon, authenticated;
revoke all on public.game_cities from anon, authenticated;

insert into public.game_regions(region_key,name,region_type,island_group,metadata)
values
('jawa-barat','Jawa Barat','province','Jawa','{}'),
('jawa-tengah','Jawa Tengah','province','Jawa','{}'),
('diy','DI Yogyakarta','special_region','Jawa','{}'),
('jawa-timur','Jawa Timur','province','Jawa','{}'),
('banten','Banten','province','Jawa','{}'),
('dki-jakarta','DKI Jakarta','special_region','Jawa','{}'),
('sumatera-utara','Sumatera Utara','province','Sumatera','{}'),
('sumatera-selatan','Sumatera Selatan','province','Sumatera','{}'),
('riau','Riau','province','Sumatera','{"role":"regional_economic_area"}'),
('bali','Bali','province','Bali-Nusa Tenggara','{}'),
('kalimantan-timur','Kalimantan Timur','province','Kalimantan','{}'),
('sulawesi-selatan','Sulawesi Selatan','province','Sulawesi','{"verified_data_source":"BPS Kota Makassar"}'),
('papua','Papua','province','Maluku-Papua','{"verified_data_source":"BPS Kota Jayapura"}')
on conflict(region_key) do update set name=excluded.name, region_type=excluded.region_type, island_group=excluded.island_group, metadata=excluded.metadata, updated_at=now();

with r as (
 select id, region_key from public.game_regions
)
insert into public.game_cities(
 city_key,name,region_id,city_type,
 gdp_current_idr,gdp_constant_idr,gdp_year,gdp_growth_pct,
 minimum_wage_idr,minimum_wage_year,data_status,
 geography,economy_profile,human_resources,natural_resources,political_profile,metadata
)
select * from (
 values
 ('jakarta','Jakarta',(select id from r where region_key='dki-jakarta'),'city',null,null,null,null,null,null,'legacy_pending','{"notes":"Legacy city; economic profile will be source-backed in later Phase 1 batches}','{}','{}','{}','{}','{}'),
 ('bandung','Bandung',(select id from r where region_key='jawa-barat'),'city',null,null,null,null,null,null,'legacy_pending','{}','{}','{}','{}','{}','{}'),
 ('semarang','Semarang',(select id from r where region_key='jawa-tengah'),'city',null,null,null,null,null,null,'legacy_pending','{}','{}','{}','{}','{}','{}'),
 ('yogyakarta','Yogyakarta',(select id from r where region_key='diy'),'city',null,null,null,null,null,null,'legacy_pending','{}','{}','{}','{}','{}','{}'),
 ('surabaya','Surabaya',(select id from r where region_key='jawa-timur'),'city',null,null,null,null,null,null,'legacy_pending','{}','{}','{}','{}','{}','{}'),
 ('malang','Malang',(select id from r where region_key='jawa-timur'),'city',null,null,null,null,null,null,'legacy_pending','{}','{}','{}','{}','{}','{}'),
 ('tangerang','Tangerang',(select id from r where region_key='banten'),'city',null,null,null,null,null,null,'legacy_pending','{}','{}','{}','{}','{}','{}'),
 ('medan','Medan',(select id from r where region_key='sumatera-utara'),'city',null,null,null,null,null,null,'legacy_pending','{}','{}','{}','{}','{}','{}'),
 ('palembang','Palembang',(select id from r where region_key='sumatera-selatan'),'city',null,null,null,null,null,null,'legacy_pending','{}','{}','{}','{}','{}','{}'),
 ('pekanbaru','Pekanbaru',(select id from r where region_key='riau'),'city',
 184531850000000,90775070000000,2025,5.520,3998179,2026,'verified',
 '{"regional_position":"ibu kota Provinsi Riau","geography":"central Riau, Sumatra"}',
 '{"strengths":["perdagangan","konstruksi","industri pengolahan","jasa"],"gdp_source":"BPS 2025"}',
 '{"population_context":"sekitar 1,14 juta pada 2024","productive_age_share_pct":71,"human_capital_note":"IPM 84,26 pada 2024"}',
 '{"notes":"Tidak bertumpu pada SDA kota; posisi strategis dan SDM menjadi modal ekonomi"}',
 '{"government_level":"kota","province":"Riau"}',
 '{"source_year":2025,"source_note":"PDRB ADHB 2025 Rp184,53185 triliun; PDRB ADHK 2025 Rp90,77507 triliun; pertumbuhan 5,52%"}'),
 ('denpasar','Denpasar',(select id from r where region_key='bali'),'city',null,null,null,null,null,null,'legacy_pending','{}','{}','{}','{}','{}','{}'),
 ('balikpapan','Balikpapan',(select id from r where region_key='kalimantan-timur'),'city',null,null,null,null,null,null,'legacy_pending','{}','{}','{}','{}','{}','{}'),
 ('makassar','Makassar',(select id from r where region_key='sulawesi-selatan'),'city',
 261375690000000,155895570000000,2025,5.520,4148179,2026,'verified',
 '{"regional_position":"pusat perdagangan dan jasa Sulawesi Selatan","geography":"pesisir barat daya Sulawesi"}',
 '{"strengths":["perdagangan besar dan eceran","industri pengolahan","konstruksi","jasa"],"gdp_source":"BPS 2025"}',
 '{"notes":"pusat ekonomi regional dengan sektor tersier dominan"}',
 '{"notes":"wilayah pesisir; basis sumber daya mengikuti hinterland Sulawesi Selatan"}',
 '{"government_level":"kota","province":"Sulawesi Selatan"}',
 '{"source_year":2025,"source_note":"PDRB ADHB 2025 Rp261,37569 triliun; PDRB ADHK 2025 Rp155,89557 triliun"}'),
 ('jayapura','Jayapura',(select id from r where region_key='papua'),'city',
 42210000000000,26780000000000,2025,4.380,4436283,2026,'verified',
 '{"regional_position":"ibu kota Provinsi Papua","geography":"pesisir Teluk Yos Sudarso, Papua"}',
 '{"strengths":["jasa","perdagangan","pemerintahan"],"gdp_source":"BPS Kota Jayapura 2025"}',
 '{"notes":"pusat layanan pemerintahan dan jasa di Papua"}',
 '{"notes":"karakter pesisir dan hinterland Papua; sumber daya regional memengaruhi pasokan"}',
 '{"government_level":"kota","province":"Papua"}',
 '{"source_year":2025,"source_note":"PDRB ADHB 2025 Rp42,21 triliun; PDRB ADHK Rp26,78 triliun; pertumbuhan 4,38%"}')
) v(city_key,name,region_id,city_type,gdp_current_idr,gdp_constant_idr,gdp_year,gdp_growth_pct,minimum_wage_idr,minimum_wage_year,data_status,geography,economy_profile,human_resources,natural_resources,political_profile,metadata)
on conflict(city_key) do update set
 name=excluded.name, region_id=excluded.region_id, city_type=excluded.city_type,
 gdp_current_idr=excluded.gdp_current_idr, gdp_constant_idr=excluded.gdp_constant_idr,
 gdp_year=excluded.gdp_year, gdp_growth_pct=excluded.gdp_growth_pct,
 minimum_wage_idr=excluded.minimum_wage_idr, minimum_wage_year=excluded.minimum_wage_year,
 data_status=excluded.data_status, geography=excluded.geography, economy_profile=excluded.economy_profile,
 human_resources=excluded.human_resources, natural_resources=excluded.natural_resources,
 political_profile=excluded.political_profile, metadata=excluded.metadata, updated_at=now();

alter table public.game_world_state
  add column if not exists current_city_focus text,
  add column if not exists simulation_version text not null default 'phase1-batch1';

update public.game_world_state
set simulation_version='phase1-batch1',
    updated_at=now()
where id=1;
