-- WNI SIMULATOR — Phase 2 Life & Career
-- The production migration was applied as phase2_life_career_complete.
-- Scope: professions/workplaces, employment lifecycle, profession quests,
-- character lifecycle, health conditions, and player relationship mobility.

alter table public.game_jobs
  add column if not exists position_family text,
  add column if not exists responsibilities jsonb not null default '[]'::jsonb,
  add column if not exists career_path jsonb not null default '[]'::jsonb;

alter table public.game_character_jobs
  add column if not exists position_title text,
  add column if not exists responsibilities jsonb not null default '[]'::jsonb,
  add column if not exists performance smallint not null default 50 check (performance between 0 and 100),
  add column if not exists career_xp integer not null default 0 check (career_xp >= 0),
  add column if not exists position_level smallint not null default 1 check (position_level between 1 and 5),
  add column if not exists contract_type text not null default 'monthly',
  add column if not exists last_evaluated_at timestamptz;

create unique index if not exists game_character_jobs_one_active_idx
  on public.game_character_jobs(character_id) where status='active';

alter table public.game_characters drop constraint if exists game_characters_discord_user_id_key;
create unique index if not exists game_characters_one_active_per_user_guild_idx
  on public.game_characters(discord_user_id,guild_id) where status='active';

create table if not exists public.game_job_quests(
 id bigint generated by default as identity primary key,
 character_job_id bigint not null references public.game_character_jobs(id) on delete cascade,
 profession_key text not null,
 workplace_id bigint references public.game_institutions(id) on delete set null,
 trigger_type text not null,
 trigger_id bigint,
 title text not null,
 description text not null,
 objective jsonb not null default '{}'::jsonb,
 reward jsonb not null default '{}'::jsonb,
 status text not null default 'open' check(status in ('open','completed','failed','expired')),
 assigned_at timestamptz not null default now(),
 completed_at timestamptz,
 unique(character_job_id,trigger_type,trigger_id)
);

create table if not exists public.game_job_tick_log(
 id bigint generated by default as identity primary key,
 tick_key text not null unique,
 quests_created integer not null default 0,
 quests_completed integer not null default 0,
 evaluations integer not null default 0,
 notes text,
 tick_at timestamptz not null default now()
);

create table if not exists public.game_health_conditions(
 id bigint generated by default as identity primary key,
 character_id bigint not null references public.game_characters(id) on delete cascade,
 condition_type text not null,
 severity smallint not null check(severity between 1 and 5),
 status text not null default 'active' check(status in ('active','recovered')),
 onset_at timestamptz not null default now(),
 recovered_at timestamptz,
 metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.game_health_tick_log(
 id bigint generated by default as identity primary key,
 tick_key text not null unique,
 characters_checked integer not null default 0,
 conditions_created integer not null default 0,
 conditions_recovered integer not null default 0,
 tick_at timestamptz not null default now()
);

create table if not exists public.game_player_relationships(
 id bigint generated by default as identity primary key,
 character_a bigint not null references public.game_characters(id) on delete cascade,
 character_b bigint not null references public.game_characters(id) on delete cascade,
 relation_type text not null default 'teman',
 affinity smallint not null default 50 check(affinity between -100 and 100),
 status text not null default 'active' check(status in ('active','paused','ended')),
 last_interaction_at timestamptz,
 interaction_count integer not null default 0,
 distance_state text not null default 'same_city',
 metadata jsonb not null default '{}'::jsonb,
 updated_at timestamptz not null default now(),
 check(character_a<>character_b),
 unique(character_a,character_b)
);

alter table public.game_job_quests enable row level security;
alter table public.game_job_tick_log enable row level security;
alter table public.game_health_conditions enable row level security;
alter table public.game_health_tick_log enable row level security;
alter table public.game_player_relationships enable row level security;
revoke all on public.game_job_quests,public.game_job_tick_log,public.game_health_conditions,public.game_health_tick_log,public.game_player_relationships from anon,authenticated;

-- Server functions installed in production:
-- game_create_character, game_retire_character
-- game_apply_for_job, game_resign_job
-- game_run_job_quest_tick, game_complete_job_quest
-- game_run_health_tick
-- game_update_player_relationship_distance, game_interact_player_relationship
