-- WNI SIMULATOR — Phase 1 complete world foundation
-- World -> City -> Government -> Institution -> Company -> Licensing -> Employment -> Finance
-- All mutations are server-side SECURITY DEFINER; no client writes.

create table if not exists public.game_city_governments (
 id bigint generated by default as identity primary key,
 city_id bigint not null unique references public.game_cities(id) on delete restrict,
 mayor_character_id bigint references public.game_characters(id) on delete set null,
 budget bigint not null default 0 check (budget >= 0),
 approval numeric(5,2) not null default 60 check (approval between 0 and 100),
 tax_rate numeric(6,4) not null default 0.0500 check (tax_rate between 0 and 1),
 policy jsonb not null default '{}'::jsonb,
 services jsonb not null default '{"health":60,"education":60,"security":60,"infrastructure":60}'::jsonb,
 updated_at timestamptz not null default now()
);

create table if not exists public.game_institutions (
 id bigint generated by default as identity primary key,
 institution_key text not null unique,
 name text not null,
 institution_type text not null,
 city_id bigint not null references public.game_cities(id) on delete restrict,
 owner_type text not null default 'government' check (owner_type in ('government','private','community')),
 owner_character_id bigint references public.game_characters(id) on delete set null,
 business_id bigint references public.game_businesses(id) on delete set null,
 capacity integer not null default 50 check (capacity > 0),
 revenue bigint not null default 0 check (revenue >= 0),
 operating_cost bigint not null default 0 check (operating_cost >= 0),
 reputation smallint not null default 50 check (reputation between 0 and 100),
 status text not null default 'open' check (status in ('open','closed','suspended')),
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
create index if not exists game_institutions_city_idx on public.game_institutions(city_id);
create index if not exists game_institutions_type_idx on public.game_institutions(institution_type);

alter table public.game_businesses add column if not exists city_id bigint references public.game_cities(id) on delete restrict;
alter table public.game_businesses add column if not exists legal_status text not null default 'legacy_active';
alter table public.game_businesses add column if not exists police_permit_status text not null default 'not_required';
alter table public.game_businesses add column if not exists mayor_approval_status text not null default 'not_required';
alter table public.game_businesses add column if not exists discord_role_id text;
alter table public.game_businesses add column if not exists discord_channel_id text;
alter table public.game_businesses add column if not exists bank_balance bigint not null default 0;
alter table public.game_businesses add column if not exists loan_principal bigint not null default 0;
alter table public.game_businesses add column if not exists monthly_revenue bigint not null default 0;
alter table public.game_businesses add column if not exists monthly_expense bigint not null default 0;
alter table public.game_businesses add column if not exists monthly_profit bigint not null default 0;
alter table public.game_businesses add column if not exists last_payroll_period text;
create index if not exists game_businesses_city_idx on public.game_businesses(city);
create index if not exists game_businesses_legal_idx on public.game_businesses(legal_status);

create table if not exists public.game_company_applications (
 id bigint generated by default as identity primary key,
 application_key text not null unique,
 owner_character_id bigint not null references public.game_characters(id) on delete cascade,
 business_id bigint references public.game_businesses(id) on delete set null,
 company_name text not null,
 sector text not null,
 city_id bigint not null references public.game_cities(id) on delete restrict,
 capital bigint not null check (capital >= 1000000),
 police_status text not null default 'pending' check (police_status in ('pending','approved','rejected')),
 mayor_status text not null default 'pending' check (mayor_status in ('pending','approved','rejected')),
 final_status text not null default 'pending' check (final_status in ('pending','legal','illegal','rejected')),
 police_reviewed_at timestamptz,
 mayor_reviewed_at timestamptz,
 created_at timestamptz not null default now(),
 metadata jsonb not null default '{}'::jsonb
);
create index if not exists game_company_applications_owner_idx on public.game_company_applications(owner_character_id);
create index if not exists game_company_applications_city_idx on public.game_company_applications(city_id);

alter table public.game_character_jobs add column if not exists employer_business_id bigint references public.game_businesses(id) on delete set null;
alter table public.game_character_jobs add column if not exists employer_institution_id bigint references public.game_institutions(id) on delete set null;
create index if not exists game_character_jobs_employer_idx on public.game_character_jobs(employer_business_id);

create table if not exists public.game_business_finance_periods (
 id bigint generated by default as identity primary key,
 business_id bigint not null references public.game_businesses(id) on delete cascade,
 period_key text not null,
 revenue bigint not null default 0,
 payroll_expense bigint not null default 0,
 operating_expense bigint not null default 0,
 loan_payment bigint not null default 0,
 tax_expense bigint not null default 0,
 net_profit bigint not null default 0,
 closing_cash bigint not null default 0,
 status text not null default 'closed',
 closed_at timestamptz not null default now(),
 unique(business_id,period_key)
);
create index if not exists game_business_finance_periods_period_idx on public.game_business_finance_periods(period_key);

-- Canonical job definitions: profession must point toward a real workplace type.
update public.game_jobs set metadata = metadata || '{"workplace_types":["company"]}'::jsonb
where metadata is null or not (metadata ? 'workplace_types');

insert into public.game_jobs(job_key,job_name,sector,base_salary,min_skill,metadata)
values
('dokter','Dokter','Kesehatan',12000000,20,'{"workplace_types":["hospital"],"quest_domain":"patient_care"}'),
('perawat','Perawat','Kesehatan',6500000,15,'{"workplace_types":["hospital"],"quest_domain":"patient_care"}'),
('guru','Guru','Pendidikan',5500000,15,'{"workplace_types":["school"],"quest_domain":"teaching"}'),
('polisi','Polisi','Hukum',6500000,20,'{"workplace_types":["police"],"quest_domain":"law_enforcement"}'),
('programmer','Programmer','Teknologi',8000000,20,'{"workplace_types":["company"],"quest_domain":"software"}'),
('chef','Chef','Kuliner',5500000,15,'{"workplace_types":["restaurant"],"quest_domain":"kitchen"}'),
('akuntan','Akuntan','Keuangan',6500000,20,'{"workplace_types":["company","bank"],"quest_domain":"finance"}'),
('arsitek','Arsitek','Konstruksi',7000000,20,'{"workplace_types":["company"],"quest_domain":"design"}')
on conflict(job_key) do update set job_name=excluded.job_name,sector=excluded.sector,base_salary=excluded.base_salary,min_skill=excluded.min_skill,metadata=excluded.metadata,active=true;

-- Seed one government and real institutions per verified Phase 1 city.
insert into public.game_city_governments(city_id,budget,approval,tax_rate,policy)
select c.id,50000000000,60,0.0500,jsonb_build_object('city_focus',c.economy_profile)
from public.game_cities c
where c.data_status='verified'
on conflict(city_id) do nothing;

insert into public.game_institutions(institution_key,name,institution_type,city_id,owner_type,capacity,revenue,operating_cost,metadata)
select 'gov-'||c.city_key,'Pemerintah Kota '||c.name,'government',c.id,'government',100,0,500000000,'{"system":"city_government"}'::jsonb
from public.game_cities c where c.active=true
on conflict(institution_key) do nothing;

insert into public.game_institutions(institution_key,name,institution_type,city_id,owner_type,capacity,metadata)
select x.city_key||'-hospital','RS Umum '||c.name,'hospital',c.id,'private',300,'{"jobs":["dokter","perawat"]}'::jsonb
from public.game_cities c join (select city_key from public.game_cities) x on x.city_key=c.city_key
where c.active=true
on conflict(institution_key) do nothing;

insert into public.game_institutions(institution_key,name,institution_type,city_id,owner_type,capacity,metadata)
select c.city_key||'-school','Sekolah Umum '||c.name,'school',c.id,'government',500,'{"jobs":["guru"]}'::jsonb
from public.game_cities c where c.active=true
on conflict(institution_key) do nothing;

insert into public.game_institutions(institution_key,name,institution_type,city_id,owner_type,capacity,metadata)
select c.city_key||'-police','Polsek/Polres '||c.name,'police',c.id,'government',200,'{"jobs":["polisi"]}'::jsonb
from public.game_cities c where c.active=true
on conflict(institution_key) do nothing;

insert into public.game_institutions(institution_key,name,institution_type,city_id,owner_type,capacity,metadata)
select c.city_key||'-bank','Bank Layanan '||c.name,'bank',c.id,'private',5000,'{"jobs":["akuntan"]}'::jsonb
from public.game_cities c where c.active=true
on conflict(institution_key) do nothing;

-- Employer-aware hiring. Existing generic jobs remain valid; business employment is authoritative when linked.
create or replace function public.game_hire_employee_v2(
 p_business_id bigint,p_owner_character_id bigint,p_character_id bigint,p_job_key text,p_salary bigint
) returns jsonb language plpgsql security definer set search_path=public as $$
declare b game_businesses%rowtype; j game_jobs%rowtype; c game_characters%rowtype; city_id_v bigint; emp_id bigint;
begin
 select * into b from game_businesses where id=p_business_id and status='active' for update;
 if not found or b.owner_character_id<>p_owner_character_id then raise exception 'NOT_BUSINESS_OWNER'; end if;
 select * into c from game_characters where id=p_character_id and status='active' for update;
 if not found then raise exception 'CHARACTER_NOT_ACTIVE'; end if;
 select * into j from game_jobs where job_key=p_job_key and active=true;
 if not found then raise exception 'JOB_NOT_FOUND'; end if;
 if p_salary < 0 then raise exception 'INVALID_SALARY'; end if;
 if exists(select 1 from game_business_employees where business_id=b.id and character_id=p_character_id and status='active') then raise exception 'ALREADY_EMPLOYEE'; end if;
 if exists(select 1 from game_character_jobs where character_id=p_character_id and status='active') then raise exception 'ALREADY_EMPLOYED'; end if;
 insert into game_business_employees(business_id,character_id,role_title,salary,status)
 values(b.id,p_character_id,j.job_name,p_salary,'active') returning id into emp_id;
 insert into game_character_jobs(character_id,job_id,status,salary,skill,employer_business_id)
 values(p_character_id,j.id,'active',p_salary,0,b.id);
 return jsonb_build_object('success',true,'employee_id',emp_id,'job_name',j.job_name,'salary',p_salary,'business_id',b.id);
end $$;

-- Company registration and two-step legal approval.
create or replace function public.game_register_company(
 p_owner_character_id bigint,p_application_key text,p_name text,p_sector text,p_city_key text,p_capital bigint
) returns jsonb language plpgsql security definer set search_path=public as $$
declare c game_characters%rowtype; cityrow game_cities%rowtype; app game_company_applications%rowtype;
begin
 select * into c from game_characters where id=p_owner_character_id and status='active' for update;
 if not found then raise exception 'CHARACTER_NOT_FOUND'; end if;
 select * into cityrow from game_cities where city_key=p_city_key and active=true;
 if not found then raise exception 'CITY_NOT_FOUND'; end if;
 if p_capital<1000000 then raise exception 'CAPITAL_TOO_LOW'; end if;
 perform game_wallet_adjust(p_owner_character_id,'cash',-p_capital,'company_capital','Modal pendaftaran perusahaan',p_application_key);
 insert into game_company_applications(application_key,owner_character_id,company_name,sector,city_id,capital)
 values(p_application_key,p_owner_character_id,p_name,p_sector,cityrow.id,p_capital)
 returning * into app;
 return jsonb_build_object('success',true,'application_id',app.id,'police_status',app.police_status,'mayor_status',app.mayor_status,'final_status',app.final_status);
exception when unique_violation then raise exception 'APPLICATION_KEY_EXISTS'; end $$;

create or replace function public.game_review_company_police(p_application_id bigint,p_approve boolean) returns jsonb
language plpgsql security definer set search_path=public as $$
declare a game_company_applications%rowtype;
begin
 select * into a from game_company_applications where id=p_application_id for update;
 if not found then raise exception 'APPLICATION_NOT_FOUND'; end if;
 update game_company_applications set police_status=case when p_approve then 'approved' else 'rejected' end,police_reviewed_at=now() where id=a.id;
 return jsonb_build_object('success',true,'police_status',case when p_approve then 'approved' else 'rejected' end);
end $$;

create or replace function public.game_review_company_mayor(p_application_id bigint,p_approve boolean) returns jsonb
language plpgsql security definer set search_path=public as $$
declare a game_company_applications%rowtype;
begin
 select * into a from game_company_applications where id=p_application_id for update;
 if not found then raise exception 'APPLICATION_NOT_FOUND'; end if;
 if a.police_status<>'approved' then raise exception 'POLICE_APPROVAL_REQUIRED'; end if;
 update game_company_applications set mayor_status=case when p_approve then 'approved' else 'rejected' end,mayor_reviewed_at=now() where id=a.id;
 return jsonb_build_object('success',true,'mayor_status',case when p_approve then 'approved' else 'rejected' end);
end $$;

create or replace function public.game_finalize_company(p_application_id bigint) returns jsonb
language plpgsql security definer set search_path=public as $$
declare a game_company_applications%rowtype; b game_businesses%rowtype;
begin
 select * into a from game_company_applications where id=p_application_id for update;
 if not found then raise exception 'APPLICATION_NOT_FOUND'; end if;
 if a.police_status='approved' and a.mayor_status='approved' then
   insert into game_businesses(business_key,owner_character_id,name,sector,city,cash,reputation,status,city_id,legal_status,police_permit_status,mayor_approval_status)
   select a.application_key,a.owner_character_id,a.company_name,a.sector,c.name,a.capital,50,'active',c.id,'legal','approved','approved'
   from game_cities c where c.id=a.city_id
   returning * into b;
   update game_company_applications set business_id=b.id,final_status='legal' where id=a.id;
   return jsonb_build_object('success',true,'status','legal','business_id',b.id);
 elsif a.police_status='rejected' or a.mayor_status='rejected' then
   update game_company_applications set final_status='illegal' where id=a.id;
   return jsonb_build_object('success',true,'status','illegal');
 end if;
 raise exception 'APPROVALS_PENDING';
end $$;

-- Monthly company close: revenue, payroll, operating expense, tax, profit/loss and insolvency.
create or replace function public.game_close_business_finance(p_period_key text) returns jsonb
language plpgsql security definer set search_path=public as $$
declare b record; emp record; rev bigint; payroll bigint; op bigint; tax bigint; loan bigint; profit bigint; paid int:=0; closed int:=0;
begin
 for b in select * from game_businesses where status='active' for update loop
   if exists(select 1 from game_business_finance_periods where business_id=b.id and period_key=p_period_key) then continue; end if;
   select coalesce(sum(case when transaction_type in ('sale','revenue','income') and amount>0 then amount else 0 end),0),
          coalesce(sum(case when transaction_type not in ('sale','revenue','income') and amount<0 then -amount else 0 end),0)
   into rev,op from game_business_transactions where business_id=b.id and created_at >= date_trunc('month',now());
   payroll:=0;
   for emp in select character_id,salary from game_business_employees where business_id=b.id and status='active' loop
     if b.cash >= emp.salary then
       perform game_wallet_adjust(emp.character_id,'cash',emp.salary,'business_payroll','Gaji dari '||b.name,'business-payroll:'||b.id||':'||p_period_key||':'||emp.character_id);
       b.cash:=b.cash-emp.salary; payroll:=payroll+emp.salary; paid:=paid+1;
     end if;
   end loop;
   tax:=greatest(0,round((rev-op-payroll)*0.02));
   if b.cash>=tax then b.cash:=b.cash-tax; else tax:=0; end if;
   loan:=least(b.loan_principal,greatest(0,round(b.loan_principal*0.02)));
   if b.cash>=loan then b.cash:=b.cash-loan; b.loan_principal:=b.loan_principal-loan; end if;
   profit:=rev-op-payroll-tax-loan;
   update game_businesses set cash=b.cash,monthly_revenue=rev,monthly_expense=op+payroll+tax+loan,monthly_profit=profit,last_payroll_period=p_period_key,status=case when b.cash<=0 and profit<0 then 'insolvent' else status end where id=b.id;
   insert into game_business_finance_periods(business_id,period_key,revenue,payroll_expense,operating_expense,loan_payment,tax_expense,net_profit,closing_cash)
   values(b.id,p_period_key,rev,payroll,op,loan,tax,profit,b.cash);
   closed:=closed+1;
 end loop;
 return jsonb_build_object('success',true,'period_key',p_period_key,'businesses_closed',closed,'employees_paid',paid);
end $$;

-- City simulation: GDP-derived budget pressure and unemployment snapshot.
create or replace function public.game_run_city_simulation(p_tick_key text) returns jsonb
language plpgsql security definer set search_path=public as $$
declare c record; employed int; population int; changed int:=0;
begin
 for c in select * from game_cities where active=true loop
   select count(*) into employed from game_ai_characters where alive=true and city=c.name and occupation is not null;
   select count(*) into population from game_ai_characters where alive=true and city=c.name;
   update game_city_governments g set
     approval=greatest(0,least(100,g.approval + case when population>0 and employed::numeric/population < 0.55 then -1 else 1 end)),
     updated_at=now()
   where g.city_id=c.id;
   changed:=changed+1;
 end loop;
 return jsonb_build_object('success',true,'cities_updated',changed,'tick_key',p_tick_key);
end $$;

-- Enforce server-only execution for new sensitive functions.
revoke all on function public.game_register_company(bigint,text,text,text,text,bigint) from public,anon,authenticated;
revoke all on function public.game_review_company_police(bigint,boolean) from public,anon,authenticated;
revoke all on function public.game_review_company_mayor(bigint,boolean) from public,anon,authenticated;
revoke all on function public.game_finalize_company(bigint) from public,anon,authenticated;
revoke all on function public.game_close_business_finance(text) from public,anon,authenticated;
revoke all on function public.game_run_city_simulation(text) from public,anon,authenticated;
grant execute on function public.game_register_company(bigint,text,text,text,text,bigint) to service_role;
grant execute on function public.game_review_company_police(bigint,boolean) to service_role;
grant execute on function public.game_review_company_mayor(bigint,boolean) to service_role;
grant execute on function public.game_finalize_company(bigint) to service_role;
grant execute on function public.game_close_business_finance(text) to service_role;
grant execute on function public.game_run_city_simulation(text) to service_role;
