-- Vreeo Music & Games Supabase schema
create table if not exists music_history (
 id bigint generated by default as identity primary key,
 user_id bigint not null,
 title text not null,
 source_url text,
 played_at timestamptz default now()
);
create index if not exists music_history_user_played_idx on music_history(user_id,played_at desc);

create table if not exists favorites (
 user_id bigint not null,
 title text not null,
 source_url text not null,
 created_at timestamptz default now(),
 primary key(user_id,source_url)
);

create table if not exists playlists (
 id bigint generated by default as identity primary key,
 user_id bigint not null,
 name text not null,
 created_at timestamptz default now(),
 unique(user_id,name)
);

create table if not exists playlist_tracks (
 playlist_id bigint references playlists(id) on delete cascade,
 position integer not null,
 title text not null,
 source_url text not null,
 primary key(playlist_id,position)
);
create index if not exists playlist_tracks_playlist_idx on playlist_tracks(playlist_id,position);

create table if not exists users (
 user_id bigint primary key,
 display_name text,
 created_at timestamptz default now(),
 last_seen timestamptz default now()
);
create table if not exists economy (
 user_id bigint primary key references users(user_id) on delete cascade,
 balance bigint not null default 0,
 bank bigint not null default 0
);
create table if not exists transactions (
 id bigint generated by default as identity primary key,
 user_id bigint not null,
 amount bigint not null,
 kind text not null,
 metadata jsonb default '{}'::jsonb,
 created_at timestamptz default now()
);
create table if not exists inventory (
 user_id bigint not null,
 item_key text not null,
 quantity integer not null default 0,
 primary key(user_id,item_key)
);
create table if not exists game_stats (
 user_id bigint primary key references users(user_id) on delete cascade,
 wins integer not null default 0,
 losses integer not null default 0,
 draws integer not null default 0,
 games integer not null default 0
);
create table if not exists achievements (
 key text primary key,
 name text not null,
 description text not null
);
create table if not exists user_achievements (
 user_id bigint not null,
 achievement_key text references achievements(key) on delete cascade,
 unlocked_at timestamptz default now(),
 primary key(user_id,achievement_key)
);
create table if not exists daily_rewards (
 user_id bigint primary key,
 streak integer not null default 0,
 last_claimed date
);
create table if not exists bot_settings (
 key text primary key,
 value jsonb not null default '{}'::jsonb,
 updated_at timestamptz default now()
);

alter table music_history enable row level security;
alter table favorites enable row level security;
alter table playlists enable row level security;
alter table playlist_tracks enable row level security;
alter table users enable row level security;
alter table economy enable row level security;
alter table transactions enable row level security;
alter table inventory enable row level security;
alter table game_stats enable row level security;
alter table achievements enable row level security;
alter table user_achievements enable row level security;
alter table daily_rewards enable row level security;
alter table bot_settings enable row level security;


-- Tournament Maker
create table if not exists tournaments (
 id bigint generated by default as identity primary key,
 guild_id bigint not null,
 organizer_id bigint not null,
 name text not null,
 format text not null check (format in ('league','knockout')),
 max_participants integer not null check (max_participants between 2 and 64),
 status text not null default 'registration' check (status in ('registration','active','completed','cancelled')),
 created_at timestamptz not null default now()
);
create table if not exists tournament_participants (
 tournament_id bigint not null references tournaments(id) on delete cascade,
 user_id bigint not null,
 joined_at timestamptz not null default now(),
 primary key(tournament_id,user_id)
);
create table if not exists tournament_matches (
 id bigint generated by default as identity primary key,
 tournament_id bigint not null references tournaments(id) on delete cascade,
 round_number integer not null,
 match_number integer not null,
 home_team_id bigint,
 away_team_id bigint,
 home_score integer,
 away_score integer,
 status text not null default 'scheduled' check (status in ('scheduled','completed')),
 created_at timestamptz not null default now(),
 unique(tournament_id,round_number,match_number)
);
create index if not exists tournament_participants_tournament_idx on tournament_participants(tournament_id);
create index if not exists tournament_matches_tournament_round_idx on tournament_matches(tournament_id,round_number,match_number);
alter table tournaments enable row level security;
alter table tournament_participants enable row level security;
alter table tournament_matches enable row level security;
