create table if not exists users (
  user_id bigint primary key,
  username text not null,
  created_at timestamptz not null default now(),
  xp bigint not null default 0,
  level integer not null default 1
);

create table if not exists economy (
  user_id bigint primary key references users(user_id) on delete cascade,
  balance bigint not null default 0,
  bank bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists transactions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(user_id) on delete cascade,
  amount bigint not null,
  reason text not null,
  created_at timestamptz not null default now()
);

create table if not exists game_stats (
  user_id bigint primary key references users(user_id) on delete cascade,
  games_played bigint not null default 0,
  wins bigint not null default 0,
  losses bigint not null default 0
);

create table if not exists bot_settings (
  key text primary key,
  value text not null
);

alter table users enable row level security;
alter table economy enable row level security;
alter table transactions enable row level security;
alter table game_stats enable row level security;
alter table bot_settings enable row level security;
