create table if not exists music_history (id bigint generated by default as identity primary key,user_id bigint not null,title text not null,source_url text,played_at timestamptz default now());
create table if not exists favorites (user_id bigint not null,title text not null,source_url text not null,created_at timestamptz default now(),primary key(user_id,source_url));
create table if not exists playlists (id bigint generated by default as identity primary key,user_id bigint not null,name text not null,created_at timestamptz default now(),unique(user_id,name));
create table if not exists playlist_tracks (playlist_id bigint references playlists(id) on delete cascade,position integer not null,title text not null,source_url text not null,primary key(playlist_id,position));
