-- Tournament Maker schema
create table if not exists tournaments (
 id bigint generated by default as identity primary key,
 guild_id bigint not null,
 organizer_id bigint not null,
 name text not null,
 format text not null check (format in ('league','knockout')),
 max_participants integer not null check (max_participants between 2 and 64),
 status text not null default 'registration' check (status in ('registration','active','completed','cancelled')),
 created_at timestamptz not null default now()
);

create table if not exists tournament_participants (
 tournament_id bigint not null references tournaments(id) on delete cascade,
 user_id bigint not null,
 joined_at timestamptz not null default now(),
 primary key(tournament_id,user_id)
);

create table if not exists tournament_matches (
 id bigint generated by default as identity primary key,
 tournament_id bigint not null references tournaments(id) on delete cascade,
 round_number integer not null,
 match_number integer not null,
 home_team_id bigint,
 away_team_id bigint,
 home_score integer,
 away_score integer,
 status text not null default 'scheduled' check (status in ('scheduled','completed')),
 created_at timestamptz not null default now(),
 unique(tournament_id,round_number,match_number)
);

create index if not exists tournament_participants_tournament_idx on tournament_participants(tournament_id);
create index if not exists tournament_matches_tournament_round_idx on tournament_matches(tournament_id,round_number,match_number);

alter table tournaments enable row level security;
alter table tournament_participants enable row level security;
alter table tournament_matches enable row level security;
