-- WNI SIMULATOR Batch 11: Government, Politics & Society
create table if not exists game_policies (
  id bigint generated by default as identity primary key,
  policy_key text not null unique,
  name text not null,
  category text not null,
  description text not null,
  fiscal_cost bigint not null default 0,
  approval_effect integer not null default 0 check (approval_effect between -100 and 100),
  economic_effect numeric(6,3) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists game_elections (
  id bigint generated by default as identity primary key,
  government_id bigint not null references game_government(id) on delete cascade,
  election_type text not null check (election_type in ('national','regional','local')),
  status text not null default 'scheduled' check (status in ('scheduled','campaign','voting','counting','completed','cancelled')),
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  winner_character_id bigint references game_ai_characters(id) on delete set null,
  turnout numeric(6,4) not null default 0 check (turnout between 0 and 1),
  created_at timestamptz not null default now()
);

create table if not exists game_election_candidates (
  election_id bigint not null references game_elections(id) on delete cascade,
  character_id bigint not null references game_ai_characters(id) on delete cascade,
  platform jsonb not null default '{}'::jsonb,
  campaign_score numeric(6,2) not null default 50 check (campaign_score between 0 and 100),
  votes bigint not null default 0 check (votes >= 0),
  status text not null default 'active' check (status in ('active','withdrawn','disqualified')),
  primary key (election_id, character_id)
);

create table if not exists game_election_votes (
  id bigint generated by default as identity primary key,
  election_id bigint not null references game_elections(id) on delete cascade,
  voter_character_id bigint not null references game_ai_characters(id) on delete cascade,
  candidate_character_id bigint not null,
  created_at timestamptz not null default now(),
  unique(election_id,voter_character_id)
);

create table if not exists game_government_ticks (
  id bigint generated by default as identity primary key,
  tick_key text not null unique,
  tick_at timestamptz not null default now(),
  policies_applied integer not null default 0,
  elections_started integer not null default 0,
  votes_cast integer not null default 0,
  elections_completed integer not null default 0,
  approval_changes integer not null default 0,
  notes text
);

create index if not exists game_elections_status_idx on game_elections(status);
create index if not exists game_elections_government_idx on game_elections(government_id);
create index if not exists game_election_candidates_character_idx on game_election_candidates(character_id);
create index if not exists game_election_votes_election_idx on game_election_votes(election_id);

alter table game_policies enable row level security;
alter table game_elections enable row level security;
alter table game_election_candidates enable row level security;
alter table game_election_votes enable row level security;
alter table game_government_ticks enable row level security;

revoke all on game_policies,game_elections,game_election_candidates,game_election_votes,game_government_ticks from anon,authenticated;

insert into game_policies(policy_key,name,category,description,fiscal_cost,approval_effect,economic_effect)
values
('public_health','Layanan Kesehatan','social','Memperluas layanan kesehatan publik',25000000,4,0.020),
('infrastructure','Infrastruktur','economy','Meningkatkan belanja infrastruktur',50000000,5,0.040),
('education','Pendidikan','social','Meningkatkan anggaran pendidikan',35000000,4,0.025),
('tax_relief','Keringanan Pajak','fiscal','Mengurangi beban pajak masyarakat',30000000,6,0.015),
('budget_cut','Efisiensi Anggaran','fiscal','Mengurangi belanja pemerintah',0,-4,-0.010)
on conflict(policy_key) do nothing;

-- The authoritative tick function is installed by the Supabase migration
-- wni_batch_11_government_politics_society and is granted only to service_role.
