-- WNI SIMULATOR world schema
create table if not exists game_world_state (
  id smallint primary key default 1 check (id=1),
  world_name text not null default 'WNI SIMULATOR🇮🇩🦅',
  world_time timestamptz not null default now(),
  real_seconds_per_game_day bigint not null default 604800,
  ai_population_target integer not null default 250,
  economy_multiplier numeric(12,4) not null default 1.0,
  inflation_rate numeric(8,5) not null default 0,
  paused boolean not null default false,
  updated_at timestamptz not null default now()
);
insert into game_world_state(id) values (1) on conflict (id) do nothing;

create table if not exists game_ai_characters (
  id bigint generated by default as identity primary key,
  external_key text unique not null,
  name text not null,
  age integer not null check (age between 0 and 120),
  gender text not null,
  occupation text,
  city text,
  personality jsonb not null default '{}'::jsonb,
  goals jsonb not null default '[]'::jsonb,
  wallet bigint not null default 0,
  alive boolean not null default true,
  created_at timestamptz not null default now(),
  last_simulated_at timestamptz not null default now()
);
create index if not exists game_ai_city_idx on game_ai_characters(city);
create index if not exists game_ai_alive_idx on game_ai_characters(alive);

create table if not exists game_discord_bindings (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  entity_type text not null,
  entity_key text not null,
  discord_id text not null,
  discord_name text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(guild_id, entity_type, entity_key),
  unique(guild_id, discord_id)
);
create index if not exists game_discord_bindings_guild_idx on game_discord_bindings(guild_id);

create table if not exists game_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  title text not null,
  description text not null,
  severity integer not null default 1 check (severity between 1 and 5),
  city text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);
create index if not exists game_events_occurred_idx on game_events(occurred_at desc);

create table if not exists game_news (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  category text not null,
  event_id bigint references game_events(id) on delete set null,
  published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists game_news_published_idx on game_news(published, published_at desc);

alter table game_world_state enable row level security;
alter table game_ai_characters enable row level security;
alter table game_discord_bindings enable row level security;
alter table game_events enable row level security;
alter table game_news enable row level security;
