-- WNI SIMULATOR world schema
create table if not exists game_world_state (
  id smallint primary key default 1 check (id=1),
  world_name text not null default 'WNI SIMULATOR🇮🇩🦅',
  world_time timestamptz not null default now(),
  real_seconds_per_game_day bigint not null default 604800,
  ai_population_target integer not null default 250,
  economy_multiplier numeric(12,4) not null default 1.0,
  inflation_rate numeric(8,5) not null default 0,
  paused boolean not null default false,
  updated_at timestamptz not null default now()
);
insert into game_world_state(id) values (1) on conflict (id) do nothing;

create table if not exists game_ai_characters (
  id bigint generated by default as identity primary key,
  external_key text unique not null,
  name text not null,
  age integer not null check (age between 0 and 120),
  gender text not null,
  occupation text,
  city text,
  personality jsonb not null default '{}'::jsonb,
  goals jsonb not null default '[]'::jsonb,
  wallet bigint not null default 0,
  alive boolean not null default true,
  created_at timestamptz not null default now(),
  last_simulated_at timestamptz not null default now()
);
create index if not exists game_ai_city_idx on game_ai_characters(city);
create index if not exists game_ai_alive_idx on game_ai_characters(alive);

create table if not exists game_discord_bindings (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  entity_type text not null,
  entity_key text not null,
  discord_id text not null,
  discord_name text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(guild_id, entity_type, entity_key),
  unique(guild_id, discord_id)
);
create index if not exists game_discord_bindings_guild_idx on game_discord_bindings(guild_id);

create table if not exists game_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  title text not null,
  description text not null,
  severity integer not null default 1 check (severity between 1 and 5),
  city text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);
create index if not exists game_events_occurred_idx on game_events(occurred_at desc);

create table if not exists game_news (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  category text not null,
  event_id bigint references game_events(id) on delete set null,
  published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists game_news_published_idx on game_news(published, published_at desc);

alter table game_world_state enable row level security;
alter table game_ai_characters enable row level security;
alter table game_discord_bindings enable row level security;
alter table game_events enable row level security;
alter table game_news enable row level security;


-- WNI SIMULATOR Batch 1: Player Core
create table if not exists game_characters (
  id bigint generated by default as identity primary key,
  discord_user_id text not null unique,
  guild_id text not null,
  name text not null check (char_length(name) between 1 and 32),
  gender text not null check (gender in ('Laki-laki','Perempuan')),
  birth_date date not null,
  background text not null default 'Umum',
  province text not null default 'Jawa Timur',
  city text not null default 'Malang',
  district text,
  village text,
  status text not null default 'active' check (status in ('active','dead','retired')),
  health smallint not null default 100 check (health between 0 and 100),
  happiness smallint not null default 70 check (happiness between 0 and 100),
  stress smallint not null default 20 check (stress between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists game_characters_guild_idx on game_characters(guild_id);
create index if not exists game_characters_status_idx on game_characters(status);

create table if not exists game_wallets (
  id bigint generated by default as identity primary key,
  character_id bigint not null unique references game_characters(id) on delete cascade,
  cash bigint not null default 0 check (cash >= 0),
  bank bigint not null default 0 check (bank >= 0),
  debt bigint not null default 0 check (debt >= 0),
  currency text not null default 'IDR',
  updated_at timestamptz not null default now()
);
create table if not exists game_transactions (
  id bigint generated by default as identity primary key,
  wallet_id bigint not null references game_wallets(id) on delete cascade,
  account_type text not null check (account_type in ('cash','bank','debt')),
  amount bigint not null,
  balance_after bigint not null check (balance_after >= 0),
  transaction_type text not null,
  description text not null,
  reference_key text,
  created_at timestamptz not null default now()
);
create index if not exists game_transactions_wallet_time_idx on game_transactions(wallet_id, created_at desc);
create table if not exists game_inventory (
  id bigint generated by default as identity primary key,
  character_id bigint not null references game_characters(id) on delete cascade,
  item_key text not null,
  item_name text not null,
  quantity bigint not null default 1 check (quantity >= 0),
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(character_id,item_key)
);
create table if not exists game_asset_templates (
  id bigint generated by default as identity primary key,
  asset_key text not null unique,
  category text not null,
  name text not null,
  base_price bigint not null check (base_price >= 0),
  metadata jsonb not null default '{}'::jsonb,
  active boolean not null default true
);
create table if not exists game_owned_assets (
  id bigint generated by default as identity primary key,
  character_id bigint not null references game_characters(id) on delete cascade,
  template_id bigint not null references game_asset_templates(id),
  purchase_price bigint not null check (purchase_price >= 0),
  condition smallint not null default 100 check (condition between 0 and 100),
  location text,
  acquired_at timestamptz not null default now(),
  status text not null default 'owned' check (status in ('owned','sold','destroyed','seized')),
  metadata jsonb not null default '{}'::jsonb
);
create table if not exists game_needs (
  character_id bigint primary key references game_characters(id) on delete cascade,
  hunger smallint not null default 80 check (hunger between 0 and 100),
  thirst smallint not null default 80 check (thirst between 0 and 100),
  energy smallint not null default 80 check (energy between 0 and 100),
  health smallint not null default 100 check (health between 0 and 100),
  happiness smallint not null default 70 check (happiness between 0 and 100),
  stress smallint not null default 20 check (stress between 0 and 100),
  updated_at timestamptz not null default now()
);
alter table game_characters enable row level security;
alter table game_wallets enable row level security;
alter table game_transactions enable row level security;
alter table game_inventory enable row level security;
alter table game_asset_templates enable row level security;
alter table game_owned_assets enable row level security;
alter table game_needs enable row level security;


-- WNI SIMULATOR Batch 8: Autonomous NPC Life
alter table game_ai_characters
  add column if not exists energy smallint not null default 80 check (energy between 0 and 100),
  add column if not exists hunger smallint not null default 20 check (hunger between 0 and 100),
  add column if not exists happiness smallint not null default 70 check (happiness between 0 and 100),
  add column if not exists stress smallint not null default 20 check (stress between 0 and 100),
  add column if not exists current_activity text not null default 'idle',
  add column if not exists last_activity_at timestamptz;
create index if not exists game_ai_characters_autonomy_idx on game_ai_characters(alive,last_simulated_at);


-- WNI SIMULATOR Batch 9: Economic Simulation Engine
alter table game_world_state
  add column if not exists economic_index numeric(6,3) not null default 1.000,
  add column if not exists unemployment_rate numeric(6,4) not null default 0.0000,
  add column if not exists average_npc_wallet bigint not null default 0,
  add column if not exists last_economic_tick timestamptz;


-- WNI SIMULATOR Batch 10: Law, Crime & Justice
create table if not exists game_law_agencies (
  id bigint generated by default as identity primary key,
  agency_key text not null unique,
  name text not null,
  city text,
  enforcement_power numeric(5,2) not null default 70 check (enforcement_power between 0 and 100),
  investigation_skill numeric(5,2) not null default 70 check (investigation_skill between 0 and 100),
  justice_efficiency numeric(5,2) not null default 70 check (justice_efficiency between 0 and 100),
  corruption_rate numeric(5,4) not null default 0.0500 check (corruption_rate between 0 and 1),
  budget bigint not null default 0,
  updated_at timestamptz not null default now()
);
create table if not exists game_law_profiles (
  character_id bigint primary key references game_ai_characters(id) on delete cascade,
  wanted_level smallint not null default 0 check (wanted_level between 0 and 5),
  convictions integer not null default 0 check (convictions >= 0),
  active_sentence_until timestamptz,
  last_offense_at timestamptz,
  updated_at timestamptz not null default now()
);
create table if not exists game_justice_cases (
  id bigint generated by default as identity primary key,
  crime_event_id bigint not null unique references game_crime_events(id) on delete cascade,
  character_id bigint references game_ai_characters(id) on delete set null,
  status text not null default 'investigating' check (status in ('investigating','arrested','trial','convicted','acquitted','dismissed','served')),
  evidence_score numeric(5,2) not null default 0 check (evidence_score between 0 and 100),
  fine_amount bigint not null default 0 check (fine_amount >= 0),
  sentence_hours integer not null default 0 check (sentence_hours >= 0),
  opened_at timestamptz not null default now(),
  resolved_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);
create table if not exists game_justice_sentences (
  id bigint generated by default as identity primary key,
  case_id bigint not null unique references game_justice_cases(id) on delete cascade,
  character_id bigint references game_ai_characters(id) on delete set null,
  sentence_type text not null default 'penjara' check (sentence_type in ('penjara','denda','penjara_dan_denda')),
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  fine_amount bigint not null default 0 check (fine_amount >= 0),
  status text not null default 'active' check (status in ('active','completed')),
  created_at timestamptz not null default now()
);
create table if not exists game_law_ticks (
  id bigint generated by default as identity primary key,
  tick_key text not null unique,
  tick_at timestamptz not null default now(),
  crimes_opened integer not null default 0,
  investigations_advanced integer not null default 0,
  arrests integer not null default 0,
  trials integer not null default 0,
  convictions integer not null default 0,
  acquittals integer not null default 0,
  sentences_completed integer not null default 0,
  notes text
);
create index if not exists game_justice_cases_status_idx on game_justice_cases(status);
create index if not exists game_justice_cases_character_idx on game_justice_cases(character_id);
create index if not exists game_justice_sentences_status_idx on game_justice_sentences(status);
create index if not exists game_justice_sentences_character_idx on game_justice_sentences(character_id);
create index if not exists game_crime_events_status_idx on game_crime_events(status);
