-- WNI SIMULATOR Batch 7: NPC Memory & Reputation
create table if not exists game_ai_memories (
  id bigint generated by default as identity primary key,
  character_id bigint not null references game_ai_characters(id) on delete cascade,
  subject_type text not null,
  subject_id text not null,
  memory_type text not null,
  summary text not null,
  emotional_weight smallint not null default 0 check (emotional_weight between -100 and 100),
  importance smallint not null default 50 check (importance between 1 and 100),
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  last_recalled_at timestamptz,
  recall_count integer not null default 0 check (recall_count >= 0),
  unique(character_id, subject_type, subject_id, memory_type)
);
create index if not exists game_ai_memories_character_time_idx on game_ai_memories(character_id, occurred_at desc);
create index if not exists game_ai_memories_subject_idx on game_ai_memories(subject_type, subject_id);

create table if not exists game_ai_reputations (
  id bigint generated by default as identity primary key,
  observer_character_id bigint not null references game_ai_characters(id) on delete cascade,
  subject_type text not null,
  subject_id text not null,
  reputation_score smallint not null default 0 check (reputation_score between -100 and 100),
  trust_score smallint not null default 0 check (trust_score between -100 and 100),
  respect_score smallint not null default 0 check (respect_score between -100 and 100),
  familiarity smallint not null default 0 check (familiarity between 0 and 100),
  interactions_count integer not null default 0 check (interactions_count >= 0),
  metadata jsonb not null default '{}'::jsonb,
  last_interaction_at timestamptz,
  updated_at timestamptz not null default now(),
  unique(observer_character_id, subject_type, subject_id)
);
create index if not exists game_ai_reputations_observer_idx on game_ai_reputations(observer_character_id, reputation_score desc);
create index if not exists game_ai_reputations_subject_idx on game_ai_reputations(subject_type, subject_id);

alter table game_ai_memories enable row level security;
alter table game_ai_reputations enable row level security;
