-- Batch 12: Living Indonesia World / Emergent Simulation
-- Reproducible schema for the live emergent-world engine.

create table if not exists public.game_world_events (
  id bigint generated by default as identity primary key,
  tick_key text not null unique,
  event_type text not null,
  title text not null,
  description text not null,
  city text,
  severity integer not null check (severity between 1 and 5),
  economic_effect numeric(6,3) not null default 0,
  social_effect integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create table if not exists public.game_world_event_ticks (
  id bigint generated by default as identity primary key,
  tick_key text not null unique,
  event_id bigint references public.game_world_events(id) on delete set null,
  event_generated boolean not null default false,
  affected_npcs integer not null default 0,
  notes text,
  tick_at timestamptz not null default now()
);

create index if not exists idx_game_world_events_city on public.game_world_events(city);
create index if not exists idx_game_world_events_type on public.game_world_events(event_type);

alter table public.game_world_events enable row level security;
alter table public.game_world_event_ticks enable row level security;
revoke all on public.game_world_events from anon, authenticated;
revoke all on public.game_world_event_ticks from anon, authenticated;

create or replace function public.game_run_world_event_tick(p_tick_key text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_exists public.game_world_event_ticks%rowtype;
  v_event_id bigint;
  v_city text;
  v_roll integer;
  v_type text;
  v_title text;
  v_desc text;
  v_severity integer;
  v_econ numeric(6,3);
  v_social integer;
  v_affected integer := 0;
  v_game_event_id bigint;
begin
  if p_tick_key is null or length(trim(p_tick_key)) = 0 then
    raise exception 'tick_key required';
  end if;

  select * into v_exists
  from public.game_world_event_ticks
  where tick_key = p_tick_key;

  if found then
    return jsonb_build_object(
      'idempotent', true,
      'tick_key', p_tick_key,
      'event_generated', v_exists.event_generated
    );
  end if;

  v_roll := mod(('x'||substr(md5(p_tick_key),1,8))::bit(32)::bigint,100);

  select c.city into v_city
  from public.game_ai_characters c
  where c.alive and c.city is not null
  group by c.city
  order by md5(p_tick_key||c.city)
  limit 1;

  if v_roll < 18 then
    v_type := 'economic_boom';
    v_title := 'Ledakan Aktivitas Ekonomi';
    v_desc := 'Aktivitas ekonomi lokal meningkat dan membuka lebih banyak peluang kerja.';
    v_severity := 2; v_econ := 0.035; v_social := 5;
  elsif v_roll < 32 then
    v_type := 'flood';
    v_title := 'Banjir Lokal';
    v_desc := 'Banjir mengganggu aktivitas warga dan menekan produktivitas sementara.';
    v_severity := 3; v_econ := -0.045; v_social := -8;
  elsif v_roll < 44 then
    v_type := 'festival';
    v_title := 'Festival Kota';
    v_desc := 'Kegiatan budaya meningkatkan kebahagiaan dan aktivitas sosial warga.';
    v_severity := 1; v_econ := 0.018; v_social := 10;
  elsif v_roll < 55 then
    v_type := 'heatwave';
    v_title := 'Gelombang Panas';
    v_desc := 'Cuaca ekstrem menurunkan energi warga dan mengganggu sebagian aktivitas.';
    v_severity := 2; v_econ := -0.018; v_social := -4;
  elsif v_roll < 65 then
    v_type := 'food_supply';
    v_title := 'Pasokan Pangan Lancar';
    v_desc := 'Distribusi pangan membaik sehingga tekanan kebutuhan pokok menurun.';
    v_severity := 1; v_econ := 0.025; v_social := 6;
  else
    insert into public.game_world_event_ticks(tick_key,event_generated,affected_npcs,notes)
    values(p_tick_key,false,0,'no major emergent event');
    return jsonb_build_object(
      'idempotent', false,
      'event_generated', false,
      'tick_key', p_tick_key
    );
  end if;

  insert into public.game_world_events(
    tick_key,event_type,title,description,city,severity,
    economic_effect,social_effect,metadata
  )
  values(
    p_tick_key,v_type,v_title,v_desc,v_city,v_severity,
    v_econ,v_social,jsonb_build_object('roll',v_roll)
  )
  returning id into v_event_id;

  insert into public.game_events(event_type,title,description,severity,city,metadata)
  values(
    v_type,v_title,v_desc,v_severity,v_city,
    jsonb_build_object('world_event_id',v_event_id)
  )
  returning id into v_game_event_id;

  insert into public.game_news(title,body,category,event_id,published,published_at)
  values(v_title,v_desc,'world',v_game_event_id,true,now());

  update public.game_world_state
  set economic_index = greatest(0.500,least(2.000,economic_index+v_econ)),
      updated_at = now()
  where id = 1;

  update public.game_ai_characters c
  set happiness = greatest(0,least(100,c.happiness+v_social)),
      energy = greatest(0,least(100,c.energy+case when v_type='heatwave' then -8 else 0 end)),
      stress = greatest(0,least(100,c.stress-case when v_type in ('festival','food_supply','economic_boom') then 4 else 0 end))
  where c.alive and (v_city is null or c.city=v_city);

  get diagnostics v_affected = row_count;

  insert into public.game_world_event_ticks(
    tick_key,event_id,event_generated,affected_npcs,notes
  )
  values(p_tick_key,v_event_id,true,v_affected,'emergent world event applied');

  return jsonb_build_object(
    'idempotent',false,
    'event_generated',true,
    'event_id',v_event_id,
    'event_type',v_type,
    'city',v_city,
    'affected_npcs',v_affected,
    'economic_effect',v_econ,
    'social_effect',v_social
  );
end;
$function$;

revoke all on function public.game_run_world_event_tick(text) from public, anon, authenticated;
grant execute on function public.game_run_world_event_tick(text) to service_role;

create or replace function public.game_world_event_after_tick()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  perform public.game_run_world_event_tick(NEW.tick_key||'-events');
  return NEW;
end;
$function$;

revoke all on function public.game_world_event_after_tick() from public, anon, authenticated;

drop trigger if exists trg_game_world_event_after_tick on public.game_world_ticks;
create trigger trg_game_world_event_after_tick
after insert on public.game_world_ticks
for each row
execute function public.game_world_event_after_tick();
